// @generated
// This file is @generated by prost-build.
/// A raw ERC-20 amount, kept as a big-endian byte string rather than a native
/// integer type: EVM uint256 does not fit in any protobuf scalar without a
/// lossy cast, and a byte string round-trips exactly through any consumer's
/// own bignum library.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BigInt {
    #[prost(bytes="vec", tag="1")]
    pub bytes: ::prost::alloc::vec::Vec<u8>,
}
/// Emitted by `deposit()` and `mint()` — EIP-4626's
/// `event Deposit(address indexed sender, address indexed owner, uint256 assets, uint256 shares)`.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Deposit {
    /// The vault contract that emitted this event. Present on every message
    /// because this module watches every conforming vault, not one.
    #[prost(string, tag="1")]
    pub vault: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub sender: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub owner: ::prost::alloc::string::String,
    #[prost(message, optional, tag="4")]
    pub assets: ::core::option::Option<BigInt>,
    #[prost(message, optional, tag="5")]
    pub shares: ::core::option::Option<BigInt>,
    #[prost(string, tag="6")]
    pub tx_hash: ::prost::alloc::string::String,
    #[prost(uint64, tag="7")]
    pub block_number: u64,
    #[prost(uint64, tag="8")]
    pub block_timestamp: u64,
    #[prost(uint32, tag="9")]
    pub log_index: u32,
}
/// Emitted by `withdraw()` and `redeem()` — EIP-4626's
/// `event Withdraw(address indexed sender, address indexed receiver, address indexed owner, uint256 assets, uint256 shares)`.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Withdraw {
    #[prost(string, tag="1")]
    pub vault: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub sender: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub receiver: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub owner: ::prost::alloc::string::String,
    #[prost(message, optional, tag="5")]
    pub assets: ::core::option::Option<BigInt>,
    #[prost(message, optional, tag="6")]
    pub shares: ::core::option::Option<BigInt>,
    #[prost(string, tag="7")]
    pub tx_hash: ::prost::alloc::string::String,
    #[prost(uint64, tag="8")]
    pub block_number: u64,
    #[prost(uint64, tag="9")]
    pub block_timestamp: u64,
    #[prost(uint32, tag="10")]
    pub log_index: u32,
}
/// All ERC-4626 flow events observed in one block, across every vault that
/// emitted one. The unit a Substreams `map` module actually returns per block.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct VaultFlows {
    #[prost(message, repeated, tag="1")]
    pub deposits: ::prost::alloc::vec::Vec<Deposit>,
    #[prost(message, repeated, tag="2")]
    pub withdraws: ::prost::alloc::vec::Vec<Withdraw>,
}
// @@protoc_insertion_point(module)
