#!/usr/bin/env bash
# Point an operator's solver at the vault(s) they created on /earn and print how to run it.
#
#   scripts/operator-env.sh b --sepolia 0xVault --arc 0xVault [--graph SEPOLIA_URL ARC_URL]
#
# --graph switches that solver to Subgraph Studio (OBSERVATION_SOURCE=graph) until the Nest is
# re-seeded; omit it to read Arcaidia's Nest (the default).
set -euo pipefail
op=${1:?operator letter (b|c)}; shift
file=".env.solver-$op"; [ -f "$file" ] || { echo "$file missing (generated by WP-31)"; exit 1; }
set_kv() { # key value — replace or append, keeping the file readable
  if grep -qE "^#? ?$1=" "$file"; then sed -i '' -E "s|^#? ?$1=.*|$1=$2|" "$file"; else echo "$1=$2" >> "$file"; fi
}
while [ $# -gt 0 ]; do
  case "$1" in
    --sepolia) set_kv ETHEREUM_SEPOLIA_LIQUIDITY_VAULT "$2"; shift 2;;
    --arc)     set_kv ARC_TESTNET_LIQUIDITY_VAULT "$2"; shift 2;;
    --graph)   set_kv OBSERVATION_SOURCE graph; set_kv SUBGRAPH_URL_ETHEREUM_SEPOLIA "$2"; set_kv SUBGRAPH_URL_ARC_TESTNET "$3"; shift 3;;
    *) echo "unknown arg $1"; exit 1;;
  esac
done
signer=$(grep -E "^LOCAL_AGENT_PRIVATE_KEY=" "$file" | cut -d= -f2 | xargs cast wallet address --private-key)
submitter=$(grep -E "^LOCAL_SUBMITTER_PRIVATE_KEY=" "$file" | cut -d= -f2 | xargs cast wallet address --private-key)
echo "== $file"; grep -vE "PRIVATE_KEY" "$file"
echo
echo "signer (authorise this on /earn step 4): $signer"
echo "submitter (needs gas):                     $submitter"
echo
echo "run locally:   pnpm solver:start:$op"
echo "run in docker: docker compose --profile solver-$op up --build -d && docker compose logs -f arcaidia-solver-$op"
